//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.CompilerServices;
    using System.Web.Mvc;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tblTicket
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblTicket()
        {
            this.tblTicketHistories = new HashSet<tblTicketHistory>();
        }

        public tblTicket(int intConstructorNumber)
        {
            this.tblTicketHistories = new HashSet<tblTicketHistory>();
        }

        public string formattedDate { get; set; }

        public int idsTicket { get; set; }
        public int idsSeverityType { get; set; }

        [DisplayFormat(DataFormatString = "{0:d}")]
        public System.DateTime dtmCreate { get; set; }

        public int idsUserCreate { get; set; }
        public string txtIssue { get; set; }
        public bool blnResolved { get; set; }
    
        public virtual tblUser tblUser { get; set; }
        public virtual tlkpSeverityType tlkpSeverityType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTicketHistory> tblTicketHistories { get; set; }
    }
}
