//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketSystem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ticketTrackerEntities : DbContext
    {
        public ticketTrackerEntities()
            : base("name=ticketTrackerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblTicket> tblTickets { get; set; }
        public virtual DbSet<tblTicketHistory> tblTicketHistories { get; set; }
        public virtual DbSet<tblUser> tblUsers { get; set; }
        public virtual DbSet<tlkpSeverityType> tlkpSeverityTypes { get; set; }
        public virtual DbSet<tlkpUserType> tlkpUserTypes { get; set; }
    }
}
